### ISSUE TITLE
shape parameter

### ISSUE THREAD

**Issue by lkonya2024** [baddstats/goftest#5]
Dear Authors,

I have tried to use ad.test for the Weibull distribution (ad.test(D, null = "weibull", estimated = TRUE), but I got an error message (Error in F0(x, ...) : argument "shape" is missing, with no default). I thought that the program estimated all the necessary parameters from the data.
How can I make this work?

Thank you,

Laszlo

**Comment by baddstats** [comment]
This is not how it works. The algorithm does not estimate the parameters. If `estimated=TRUE` then you should provide the distribution parameters (the required arguments of `pweibull`) in the call to `ad.test`.

**Comment by lkonya2024** [comment]
Thank you very much. Now I understand and it works.
